#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

$app = new \Phare\Foundation\Micro($_ENV['APP_BASE_PATH'] ?? __DIR__);

$app->singleton(
    \Phare\Contracts\Console\Kernel::class,
    \App\Console\Kernel::class
);

$app->singleton(
    \Phare\Contracts\Debug\ExceptionHandler::class,
    \App\Exceptions\Handler::class
);

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

/** @var \Phare\Contracts\Console\Kernel $kernel */
$kernel = $app->make(\Phare\Contracts\Console\Kernel::class);

$input = new \Symfony\Component\Console\Input\ArgvInput();
$output = new \Symfony\Component\Console\Output\ConsoleOutput();

try {
    $status = $kernel->handle($input, $output);
} catch (\Throwable $e) {
    $output->writeln("<error>{$e->getMessage()}</error>");
    $output->writeln($e->getTraceAsString());
    exit(1);
}

/*
|--------------------------------------------------------------------------
| Shutdown The Application
|--------------------------------------------------------------------------
|
| Once Artisan has finished running, we will fire off the shutdown events
| so that any final work may be done by the application before we shut
| down the process. This is the last thing to happen to the request.
|
*/

$kernel->terminate($input, $status);

exit($status);
