version: "3"
services:
    db:
        image: mysql:8.0
        container_name: skeleton-db
        environment:
          TZ: "Asia/Tokyo"
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: "skeleton"
          MYSQL_USER: "skeleton"
          MYSQL_PASSWORD: "secret"
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/data:/var/lib/mysql

    php-fpm:
        build: docker/php
        container_name: skeleton-php
        environment:
            TZ: Asia/Tokyo
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/html
            - ./docker/php/config/extra.ini:/usr/local/etc/php/conf.d/extra.ini

    nginx:
        image: nginx
        container_name: skeleton-nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/conf.d:/etc/nginx/conf.d

    redis:
        image: redis:6
        container_name: skeleton-redis
        ports:
            - "6379:6379"

    phpmyadmin:
        image: phpmyadmin
        container_name: skeleton-phpmyadmin
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=skeleton-db
            - PMA_USER=skeleton
            - PMA_PASSWORD=secret
        ports:
            - "3001:80"
