-- グローバルユーザーIDとシャードIDのマッピングテーブル
CREATE TABLE mapping
(
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    shard_id   MEDIUMINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
